### PR TITLE
Default Branch

### PR DESCRIPTION
**Pull request by PookieDaCat**

### CODE REVIEW

**Comment by libsystem-ethan** [comment]
Could you please give some details about the purpose of this pull request? As far as I'm aware these changes to the default branch are not needed, as current work takes place on the master branch.

**Comment by PookieDaCat** [comment]
I was just trying to pull a distro to run in a VM.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by libsystem-ethan** [comment]
Okay, well we only have old builds running here, but we nearly have PureDarwin 16.5 ready to release, stay tuned! Old build can be found on our [old website](https://sites.google.com/a/puredarwin.org/puredarwin/). And by the way, you were probably looking for a "clone" feature.

**Comment by hideout** [comment]
thanks

2017-06-24 21:07 GMT+02:00 libsystem-ethan <notifications@github.com>:

**Comment by PookieDaCat** [comment]
Yep...you got me there.

Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request closed without merging**
