### PR TITLE
Use our own implementation of iig

### PR DESCRIPTION
**Pull request by wjk**
`iig` is currently a stub. If anyone wants to help out with making it functional, that would be much appreciated!

### CODE REVIEW

**Comment by piranna** [comment]
What's `iig` about? I can't find anything on internet about that.

**Comment by csekel** [comment]
https://developer.apple.com/forums/thread/129021 see here @piranna

**Comment by piranna** [comment]
> [developer.apple.com/forums/thread/129021](https://developer.apple.com/forums/thread/129021) see here @piranna

Still not clear to me... Maybe is it a C++ compiler with propietary extensions, and that's the reason of the need to change the extension, but otherwise the same source code content?

**Comment by wjk** [comment]
@piranna iig is a code generator that uses libclang to parse C++ header files. The “extensions” are preprocessor macros that expand to an `__attribute__` that has meaning only to iig. It then looks for those attributes and uses this information to generate several source files containing DriverKit RPC stub logic. The best documentation I can find about what it does is its own outputs.

iig is invoked by the Makefile-based xnu build process. The output headers are then consumed by some of the IOKit code. Only the barest amount of DriverKit functionality is included in xnu; the rest is in proprietary kexts. Since we don’t (yet) support DriverKit, we don’t need to recreate the entirety of iig’s functionality at this time. Unfortunately, I do not know yet what parts are required to build xnu and which are not.

**Comment by piranna** [comment]
Thanks for the explain, that's a lot more clear now :-)

**Comment by wjk** [comment]
Will have to recreate this PR due to wrong target branch. Sorry about that!

**Pull request closed without merging**
