### PR TITLE
remove link from code.google.com

### PR DESCRIPTION
**Pull request by Brouilles**
Seems superfluous, project on Github since 2014.

### CODE REVIEW

**Comment by libsystem-ethan** [comment]
I think its best that this isn't removed quite yet - some of the migration from Google Code (e.g. the wiki) is not complete, and as such it is still relevant to have a link to the old site.

**Comment by hideout** [comment]
indeed

This was sent from my Android phone.

libsystem-ethan <notifications@github.com> schrieb am Do., 27. Sep. 2018,
12:02:

**Comment by Brouilles** [comment]
I understand. I don't have access to the wiki on Google Code `401: Anonymous caller does not have storage.objects.get access to google-code-archive/v2/code.google.com/puredarwin/wikis.json.`. I'm sad because, I can migrate if you want (it's a good first step for my participation, I think).

**Comment by csekel** [comment]
@Brouilles You can go through the Wiki we have here and fix what needs to be fixed.

**Pull request closed without merging**
